### ISSUE TITLE
Android version support

### ISSUE THREAD

**Issue by AshfaqMemon** [diegosiao/cordova-plugin-android-sms-retriever#1]
Does this plugin supports android version 4.4? Also, please let me know what is minimum android version supported?

**Comment by diegosiao** [comment]
The SMS Retriever API is provided by Google Play Services client library, so the compatibility is bounded to the version of your choice (the latest is always recommended). 

From documentation:

> The SMS Retriever API is available only on Android devices with Play services version 10.2 and newer.

https://developers.google.com/identity/sms-retriever/request
