### ISSUE TITLE
unable to retrive the otp 

### ISSUE THREAD

**Issue by sonychoudhary** [diegosiao/cordova-plugin-android-sms-retriever#2]
i m unable to retrive the otp in my project the otp message is : <#> Your One Time Password for RAYD is: 7036
jCekQ1/WPYW
its getting timeout

**Comment by diegosiao** [comment]
Make sure to get the correct hash using the getAppHash() function detailed in the README file.

**Comment by sonychoudhary** [comment]
the hashcode is correct

**Comment by sonychoudhary** [comment]
i have created he hashcode using ur getAppHash() function but then also its unable to retrieve

**Comment by diegosiao** [comment]
Could you please provide more details about this issue? Like the complete console logs of calls to the success and error callbacks. Also, are you running your app on a device or emulator?

**Comment by sonychoudhary** [comment]
on device

**Comment by sonychoudhary** [comment]
hey i was able to retrieve the otp but can u tell me how to bind it with the input box
and one more issue is there that whenever the opt arrives on phone then the app crashes and restarts and sometime it retrieves and sometime it doesn't

**Comment by diegosiao** [comment]
> hey i was able to retrieve the otp but can u tell me how to bind it with the input box

I suggest you to take a look in the particular documentation of the front-end technology you choose.


> and one more issue is there that whenever the opt arrives on phone then the app crashes and restarts and sometime it retrieves and sometime it doesn't

Without more details it is not possible to provide help on this. Based on the previous question I am willing to believe you are new to mobile/Android and that is OK, here is an advice: get used to inspection on browser console but also to [**logcat**](https://developer.android.com/studio/command-line/logcat) (tool provided by Android Studio/SDK for watching the app's process events). 

I am closing this issue. Wish you luck.
