### ISSUE TITLE
Error when i build my app with this plugin

### ISSUE THREAD

**Issue by ishigo1987** [diegosiao/cordova-plugin-android-sms-retriever#3]
Hello i've this error when i'm trying to build my app with this plugin

Could not get unknown property 'PLAY_SERVICES_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler
what mean?

**Comment by SeHunLee** [comment]
> Hello i've this error when i'm trying to build my app with this plugin
> 
> Could not get unknown property 'PLAY_SERVICES_VERSION' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler
> what mean?

maybe you can resolve that problem by writing com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
to last line

**Comment by ishigo1987** [comment]
thank you but i find another solution

**Comment by zebap** [comment]
@SeHunLee  where should i add this line com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true

**Comment by zebap** [comment]
@ishigo1987 what solution u found?? i am facing same problem

**Comment by zebap** [comment]
@SeHunLee the line com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
added in build.gradle but their is no use error remains same

**Comment by ishigo1987** [comment]
@zebap  fork the plugin and change the plugin.xml contain with this
```XML
<?xml version='1.0' encoding='utf-8'?>
<plugin id="cordova-plugin-android-sms-retriever" version="1.0.4" 
    xmlns="http://apache.org/cordova/ns/plugins/1.0" 
    xmlns:android="http://schemas.android.com/apk/res/android">
    <name>cordova-plugin-android-sms-retriever</name>
    <js-module name="AndroidSmsRetriever" src="www/cordova-plugin-android-sms-retriever.js">
        <clobbers target="cordova.plugins.AndroidSmsRetriever" />
    </js-module>
    <engines>
     <engine name="cordova" version=">=6.0.0"/>
<!--      <engine name="cordova-android" version=">=6.3.0"/> -->
    </engines>
    <platform name="android">
<!--         <preference name="PLAY_SERVICES_VERSION" default="11.0.1"/> -->
        <framework src="com.google.android.gms:play-services-auth-api-phone:15.0.1" />

        <config-file parent="/*" target="res/xml/config.xml">
            <feature name="CordovaPluginAndroidSmsRetriever">
                <param name="android-package" value="org.cordova.plugin.android.sms.retriever.CordovaPluginAndroidSmsRetriever" />
            </feature>
        </config-file>
        <config-file parent="/*" target="AndroidManifest.xml"></config-file>
        <source-file src="src/android/CordovaPluginAndroidSmsRetriever.java" target-dir="src/org/cordova/plugin/android/sms/retriever/cordova-plugin-android-sms-retriever" />
    </platform>
</plugin>
```
The lines in comments is the line that you need to change from the original plugin.xml

**Comment by zebap** [comment]
tried but error remains same
