### ISSUE TITLE
Cordova Version 9 not working

### ISSUE THREAD

**Issue by rhyanbridle** [diegosiao/cordova-plugin-android-sms-retriever#4]
Hi
Since moving to the latest Cordova version 9 for Android the onSmsReceived does not seem to work anymore.

I think this has something to do with the Google services but can't seem to figure it out.

Any hints or suggestions would be helpful.

**Comment by diegosiao** [comment]
Hi @rhyanbridle 

What version of Play Services you have in your build.grade file?

E.g.:
`implementation 'com.google.android.gms:play-services-auth:17.0.0'`
`implementation 'com.google.android.gms:play-services-auth-api-phone:17.4.0'`

**Comment by rhyanbridle** [comment]
Hi Diego
Last night I remove this plugin: havesource-cordova-plugin-push and the SMS retriever works great.

My build.gradle file looks like this:

buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }

    //This replaces project.properties w.r.t. build settings
    project.ext {
      defaultBuildToolsVersion="29.0.2" //String
      defaultMinSdkVersion=22 //Integer - Minimum requirement is Android 5.1
      defaultTargetSdkVersion=29 //Integer - We ALWAYS target the latest by default
      defaultCompileSdkVersion=29 //Integer - We ALWAYS compile with the latest by default
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by rhyanbridle** [comment]
Hi Deigo

As a test last night I removed the plugin havesource-cordova-plugin-push and the sms retriever works.

in the platforms/android/app/build.gradle I see this under dependancies
dependencies {
    implementation fileTree(dir: 'libs', include: '*.jar')

    if (cdvHelpers.getConfigPreference('GradlePluginKotlinEnabled', 'false').toBoolean()) {
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    }

    // SUB-PROJECT DEPENDENCIES START
    implementation(project(path: ":CordovaLib"))
    implementation "com.google.android.gms:play-services-auth-api-phone:11.0.1"  /*<< Push plugin is putting this here*/
    implementation "com.android.support:support-v4:27.+"
    implementation "org.nanohttpd:nanohttpd:+"
    // SUB-PROJECT DEPENDENCIES END
}

**Comment by diegosiao** [comment]
So your issue is probably related with a conflict with the Play Services version, it is an old issue that Cordova developers have to deal with, different plugins may declare different versions of Play Services. Take a look at this clarifying article about this: [The Play Services Problem with Cordova Applications](https://blog.phonegap.com/the-play-services-problem-with-cordova-applications-489c9aeb2e89).

Also, this plugin uses the PLAY_SERVICES_VERSION preference that you can use to solve this problem within config.xml.

**Comment by rhyanbridle** [comment]
Thanks Diego

Appreciate the help.
